version: "3.8"

services:
  localstack:
    image: localstack/localstack:0.14.1
    container_name: localstack
    ports:
      - "4566:4566"   
    environment:
      - SERVICES=s3,dynamodb,sqs,sns,lambda,apigateway,cloudwatch
      - DEBUG=1
    volumes:
      - "./localstack-data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  backend:
    build: ./backend
    container_name: loja-backend
    ports:
      - "8080:8080"
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_ENDPOINT=http://localstack:4566
    depends_on:
      - localstack
